server:
  port: 8102
spring:
  kafka:
    bootstrap-servers: moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="mw0qp7ns" password="B3QZdEOoxokd2bX0vclUkuAGOxxygn7E";
  cloud:
   function:
      definition: walletTransaction
   stream:
      bindings:
        walletTransaction-in-0:
          destination: mw0qp7ns-wallet-transaction
  data: 
    mongodb:
      uri: mongodb+srv://erick:erickpinglo@cluster0.xdfgh.mongodb.net/bank